import { afterEach, beforeAll, beforeEach, expect, test } from "bun:test";
import { execFileSync, spawnSync } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { auditAtlas, freshnessFingerprint } from "../src/application/audit.ts";
import { ensureConfig } from "../src/application/config.ts";
import { writeAtlas } from "../src/application/generate.ts";
import { scanRepository } from "../src/application/scan.ts";
import { scanRepositoryViaRust } from "../src/infrastructure/rustScanner.ts";

const repoRoot = path.resolve(import.meta.dir, "..");
const rustBinary = path.join(repoRoot, "target/debug/groundatlas-scanner");
const generatedAt = "2026-01-01T00:00:00.000Z";
const generatorVersion = "0.1.3";

let tempRoot: string;
let fixtureRoot: string;

beforeAll(() => {
  if (!existsSync(rustBinary)) {
    execFileSync("cargo", ["build", "-p", "groundatlas-scanner"], {
      cwd: repoRoot,
      stdio: ["ignore", "pipe", "pipe"],
    });
  }
  process.env.GROUNDATLAS_RUST_SCANNER_BIN = rustBinary;
  delete process.env.GROUNDATLAS_RUST_SCANNER;
});

beforeEach(async () => {
  tempRoot = await mkdtemp(path.join(os.tmpdir(), "groundatlas-audit-parity-"));
  fixtureRoot = path.join(tempRoot, "fixture");
  execFileSync("cp", ["-R", path.resolve("test/fixtures/basic"), fixtureRoot]);
  await writeFile(path.join(fixtureRoot, ".env"), "SHOULD_NOT_BE_SCANNED=secret\n");
  execFileSync("git", ["init", "-b", "main"], { cwd: fixtureRoot });
  execFileSync("git", ["add", "."], { cwd: fixtureRoot });
  execFileSync(
    "git",
    ["-c", "user.email=test@example.com", "-c", "user.name=Test", "commit", "-m", "init"],
    { cwd: fixtureRoot },
  );
});

afterEach(async () => {
  await rm(tempRoot, { force: true, recursive: true });
});

test("auditFreshness fingerprint matches between TS and Rust scan on basic fixture", async () => {
  const tsAtlas = await scanRepository({
    cwd: fixtureRoot,
    outputDir: ".groundatlas",
    now: new Date(generatedAt),
  });
  const rustAtlas = scanRepositoryViaRust({
    cwd: fixtureRoot,
    outputDir: ".groundatlas",
    generatedAt,
    generatorVersion,
  });

  expect(freshnessFingerprint(rustAtlas)).toBe(freshnessFingerprint(tsAtlas));
});

test("auditAtlas passes when atlas was generated by TS scan and freshness uses Rust authority", async () => {
  const config = await ensureConfig(fixtureRoot);
  const atlas = await scanRepository({
    cwd: fixtureRoot,
    outputDir: config.outputDir,
    now: new Date(generatedAt),
  });
  await writeAtlas(path.join(fixtureRoot, config.outputDir), atlas);

  const audit = await auditAtlas(fixtureRoot, config.outputDir);
  expect(audit.ok).toBe(true);
});

test("auditAtlas detects stale atlas when sources change under Rust freshness authority", async () => {
  const config = await ensureConfig(fixtureRoot);
  const atlas = await scanRepository({
    cwd: fixtureRoot,
    outputDir: config.outputDir,
    now: new Date(generatedAt),
  });
  await writeAtlas(path.join(fixtureRoot, config.outputDir), atlas);
  await writeFile(
    path.join(fixtureRoot, "PROJECT.md"),
    "# Fixture Basic\n\nChanged after atlas generation.\n",
  );

  const audit = await auditAtlas(fixtureRoot, config.outputDir);
  expect(audit.ok).toBe(false);
  expect(audit.issues.some((issue) => issue.code === "stale-atlas")).toBe(true);
});

function runCliAudit(overrides: Record<string, string | undefined> = {}) {
  const env = { ...process.env, GROUNDATLAS_RUST_SCANNER_BIN: rustBinary, ...overrides };
  return spawnSync("bun", ["run", path.join(repoRoot, "src/cli.ts"), "audit", "--json"], {
    cwd: fixtureRoot,
    encoding: "utf8",
    env,
    stdio: ["ignore", "pipe", "pipe"],
  });
}

test("CLI audit uses Rust freshness authority by default", async () => {
  const config = await ensureConfig(fixtureRoot);
  const atlas = await scanRepository({
    cwd: fixtureRoot,
    outputDir: config.outputDir,
    now: new Date(generatedAt),
  });
  await writeAtlas(path.join(fixtureRoot, config.outputDir), atlas);

  delete process.env.GROUNDATLAS_RUST_SCANNER;
  const result = runCliAudit();
  expect(result.status).toBe(0);
  const payload = JSON.parse(result.stdout.trim()) as { ok: boolean };
  expect(payload.ok).toBe(true);
});

test("CLI audit can opt out freshness to TS when GROUNDATLAS_RUST_SCANNER=ts", async () => {
  const config = await ensureConfig(fixtureRoot);
  const atlas = await scanRepository({
    cwd: fixtureRoot,
    outputDir: config.outputDir,
    now: new Date(generatedAt),
  });
  await writeAtlas(path.join(fixtureRoot, config.outputDir), atlas);

  const result = runCliAudit({ GROUNDATLAS_RUST_SCANNER: "ts" });
  expect(result.status).toBe(0);
  const payload = JSON.parse(result.stdout.trim()) as { ok: boolean };
  expect(payload.ok).toBe(true);
});