export const ATLAS_SCHEMA_VERSION = 2 as const;
export const CONFIG_SCHEMA_VERSION = 1 as const;
export const DEFAULT_OUTPUT_DIR = ".groundatlas";
export const GENERATED_BANNER =
  "Generated by GroundAtlas. This is a source-grounded navigation aid, not a source of truth.";

export type SourceKind =
  | "adr"
  | "agent-adapter"
  | "build-config"
  | "ci-workflow"
  | "design-doc"
  | "documentation"
  | "generated-map"
  | "license"
  | "package-manifest"
  | "project-manifest"
  | "runbook"
  | "schema"
  | "security-policy"
  | "source"
  | "spec"
  | "test"
  | "unknown";

export type RiskSeverity = "info" | "warning" | "error";

export type GroundAtlasConfig = {
  schemaVersion: typeof CONFIG_SCHEMA_VERSION;
  outputDir: string;
  include: string[];
  exclude: string[];
  generatedDocsAreNotSsot: true;
};

export type GitState = {
  branch: string | null;
  head: string | null;
  isDirty: boolean;
  remote: string | null;
};

export type RepoIdentity = {
  name: string;
  root: string;
  git: GitState;
  packageManager: "bun" | "pnpm" | "npm" | "yarn" | "unknown";
};

export type SourceEntry = {
  path: string;
  kind: SourceKind;
  reason: string;
  canonical: boolean;
  sizeBytes: number;
  contentSha256: string;
};

export type ValidationCommand = {
  command: string;
  source: string;
  reason: string;
};

export type PublicSurface = {
  name: string;
  type: "cli" | "docs" | "manifest" | "package" | "schema" | "workflow";
  path: string;
};

export type Risk = {
  severity: RiskSeverity;
  code: string;
  message: string;
  source?: string;
};

export type TruthHome = {
  domain: string;
  owns: string;
  examples: string[];
  precedence: number;
  requiredForSylphx: boolean;
};

export type OrientationStep = {
  order: number;
  title: string;
  paths: string[];
  required: boolean;
  present: boolean;
  reason: string;
  ssotRole: string;
};

export type AtlasMap = {
  schemaVersion: typeof ATLAS_SCHEMA_VERSION;
  generatedAt: string;
  generator: {
    name: "GroundAtlas";
    version: string;
  };
  repository: RepoIdentity;
  policy: {
    generatedDocsAreNotSsot: true;
    canonicalTruthLivesIn: string[];
    writeBoundary: string;
  };
  truth: {
    model: "fact-scoped-ssot";
    conflictRule: string;
    generatedArtifactsAre: "navigation-only";
    homes: TruthHome[];
  };
  orientation: OrientationStep[];
  sources: SourceEntry[];
  publicSurfaces: PublicSurface[];
  validationCommands: ValidationCommand[];
  risks: Risk[];
};

export type ScanOptions = {
  cwd: string;
  outputDir: string;
  now?: Date;
};

export type AuditResult = {
  ok: boolean;
  issues: Risk[];
};

export type ImpactEntry = {
  path: string;
  status: string;
  matchedSources: SourceEntry[];
};
